<a href="https://colab.research.google.com/github/raju1207/Airbnb_Review_Anaylsis/blob/main/Airbnb_Review_Anaylsis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
# Load the data

df = pd.read_csv('joined_reviews_and_listings.csv')

In [3]:
df

,Unnamed: 0,listing_id,negative_sentiment,neutral_sentiment,positive_sentiment,property_type,room_type,accommodates,bathrooms,bedrooms,...,availability_90,availability_365,number_of_reviews,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,0,3353,0.026353,0.704206,0.269382,Apartment,Private room,1,1.0,1.0,...,0,249,34,9.0,8.0,9.0,9.0,9.0,9.0,0.38
1,1,5506,0.011583,0.716056,0.272389,House,Private room,2,1.0,1.0,...,69,344,36,9.0,10.0,10.0,10.0,9.0,10.0,0.40
2,2,6695,0.017319,0.732872,0.249787,Apartment,Entire home/apt,4,1.0,1.0,...,49,324,47,9.0,10.0,10.0,10.0,8.0,9.0,0.54
3,3,6976,0.010854,0.724488,0.264659,Apartment,Private room,2,1.0,1.0,...,61,319,41,10.0,9.0,10.0,10.0,9.0,10.0,0.47
4,4,8792,0.015722,0.690056,0.294278,Apartment,Entire home/apt,3,1.0,1.0,...,0,248,18,10.0,9.0,10.0,9.0,10.0,10.0,0.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3580,3580,13750763,NaN,NaN,NaN,Apartment,Private room,2,1.0,1.0,...,9,9,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3581,3581,14852179,NaN,NaN,NaN,Condominium,Private room,2,1.0,1.0,...,23,23,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3582,3582,14844274,NaN,NaN,NaN,Apartment,Private room,2,1.0,1.0,...,89,364,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3583,3583,14585486,NaN,NaN,NaN,Apartment,Entire home/apt,4,1.0,1.0,...,40,40,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3584,3584,14504422,NaN,NaN,NaN,Apartment,Private room,2,1.0,1.0,...,75,165,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3585 entries, 0 to 3584
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   3585 non-null   int64
 1   listing_id                   3585 non-null   int64
 2   negative_sentiment           2829 non-null   float64
 3   neutral_sentiment            2829 non-null   float64
 4   positive_sentiment           2829 non-null   float64
 5   property_type                3582 non-null   object
 6   room_type                    3585 non-null   object
 7   accommodates                 3585 non-null   int64
 8   bathrooms                    3571 non-null   float64
 9   bedrooms                     3575 non-null   float64
 10  beds                         3576 non-null   float64
 11  bed_type                     3585 non-null   object
 12  amenities                    3585 non-null   object
 13  price                        3585 non-null   object
 14  availability_30              3585 non-null   int64
 15  availability_60              3585 non-null   int64
 16  availability_90              3585 non-null   int64
 17  availability_365             3585 non-null   int64
 18  number_of_reviews            3585 non-null   int64
 19  review_scores_accuracy       2762 non-null   float64
 20  review_scores_cleanliness    2767 non-null   float64
 21  review_scores_checkin        2765 non-null   float64
 22  review_scores_communication  2767 non-null   float64
 23  review_scores_location       2763 non-null   float64
 24  review_scores_value          2764 non-null   float64
 25  reviews_per_month            2829 non-null   float64
dtypes: float64(13), int64(8), object(5)
memory usage: 728.3+ KB

In [ ]:
# Question 1:

What property and room types are most common among listings, and how do they correlate with review scores and guest sentiment?

In [6]:
# Find the most common property and room types
property_counts = df['property_type'].value_counts()
room_counts = df['room_type'].value_counts()

In [7]:
# Display the most common property and room types
print("Most common property types:")
print(property_counts.head())

print("\nMost common room types:")
print(room_counts.head())

Most common property types:
property_type
Apartment          2612
House               562
Condominium         231
Townhouse            54
Bed & Breakfast      41
Name: count, dtype: int64

Most common room types:
room_type
Entire home/apt    2127
Private room       1378
Shared room          80
Name: count, dtype: int64

In [9]:
# Group by property type and room type

correlation_analysis = df.groupby(['property_type', 'room_type'])[
    ['review_scores_cleanliness', 'review_scores_value', 'positive_sentiment']
].mean()

In [10]:
# Display the correlation analysis results

print("\nAverage review scores and sentiment by property and room types:")
print(correlation_analysis.sort_values(by='positive_sentiment', ascending=False).head())

Average review scores and sentiment by property and room types:
                               review_scores_cleanliness  review_scores_value  \
property_type room_type
Loft          Shared room                       9.000000             9.000000
Villa         Private room                     10.000000            10.000000
Entire Floor  Private room                     10.000000            10.000000
Loft          Private room                      8.833333             9.666667
Townhouse     Entire home/apt                   9.714286             9.428571

                               positive_sentiment
property_type room_type
Loft          Shared room                0.416786
Villa         Private room               0.344323
Entire Floor  Private room               0.331000
Loft          Private room               0.320146
Townhouse     Entire home/apt            0.319191